# Generated by Django 5.2.7 on 2025-10-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_password',
            field=models.CharField(default='qwerty', max_length=200),
            preserve_default=False,
        ),
    ]
