# Generated by Django 5.2.7 on 2025-10-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_student_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lecturer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('lecturer_name', models.CharField(max_length=100)),
                ('lecturer_email', models.EmailField(max_length=254, unique=True)),
                ('lecturer_dept', models.CharField(max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
