# Generated by Django 5.2.7 on 2025-10-24 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_given', models.DateField(auto_now_add=True)),
                ('date_due', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lecturer')),
            ],
        ),
    ]
